networks:
  luckynet:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - luckynet
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: >
      redis-server
      --appendonly yes
      --save 60 1000

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - luckynet
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  luckydraw:
    image: luckydraw:latest
    container_name: luckydraw
    networks:
      - luckynet
    depends_on:
      - redis
      - postgres
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
