apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckydraw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: luckydraw
  template:
    metadata:
      labels:
        app: luckydraw
    spec:
      containers:
      - name: luckydraw
        image: luckydraw:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: SPRING_REDIS_HOST
          value: redis
        - name: SPRING_REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: luckydraw
spec:
  type: LoadBalancer
  selector:
    app: luckydraw
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---